service: 
  name: 'new-leaderboard'

frameworkVersion: '2'

custom: 
  webpack: 
    webpackConfig: './webpack.config.js'
    includeModules: true
  
plugins:
  - serverless-webpack

provider: 
  name: 'aws'
  region: 'us-east-2' # Ohio
  runtime: 'nodejs12.x'
  memorySize: 256
  apiGateway: 
    minimumCompressionSize: 1024
  httpApi:
    payload: '1.0'
  
  environment: 
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
    CONTEST_SLUG: "lucid-internal-2020"
    HACKERRANK_AUTH: "blah"
  



functions: 
  leaderboard: 
    handler: 'handler.api'
    events:       
      - httpApi: '*'
